[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app"
version = "0.0.1"
requires-python = ">=3.11"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
